name: Create PR (Pull Shark Automation)

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *" # Run every minute

jobs:
  update-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Execute Python script
        run: python pull-shark-automation.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update progress
          title: Update progress
          branch: update-progress
          base: main
