name: 2 Merge PR (Pull Shark Automation)

on:
  pull_request:
  workflow_dispatch:

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const pull_request = context.payload.pull_request;
            if (!pull_request) {
              console.log("Pull request information not available. Exiting...");
              return;
            }
            const pull_number = pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            await github.rest.pulls.merge({
              owner: owner,
              repo: repo,
              pull_number: pull_number,
              merge_method: "merge"
            });
